language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed yofrank1/udagram-api-feed:v1
  - docker tag udagram-api-user yofrank1/udagram-api-user:v2
  - docker tag udagram-frontend yofrank1/udagram-frontend:v3
  - docker tag udagram-reverseproxy yofrank1/udagram-reverseproxy:v4 

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push udagram-api-feed yofrank1/udagram-api-feed:v1
  - docker push udagram-api-user yofrank1/udagram-api-user:v2
  - docker push udagram-frontend yofrank1/udagram-frontend:v3
  - docker push udagram-reverseproxy yofrank1/udagram-reverseproxy:v4  
